filetype off
set nocompatible
set rtp+=~/.vim/bundle/vundle
call vundle#rc()
Bundle 'gmarik/vundle'
Bundle 'tomasr/molokai'
Bundle 'hdima/python-syntax'
Bundle 'kevinw/pyflakes-vim'
Bundle 'Yggdroot/indentLine'
Bundle 'vim-scripts/matchit.zip'
Bundle 'kien/ctrlp.vim'
Bundle 'scrooloose/nerdtree'
Bundle 'scrooloose/nerdcommenter'
Bundle 'kien/rainbow_parentheses.vim'
Bundle 'Valloric/YouCompleteMe'
Bundle 'Lokaltog/vim-easymotion'
set shortmess=atl
set nu
set go=''
set confirm
set autoindent
set smartindent
set expandtab
set tabstop=4
set softtabstop=4
set shiftwidth=4
set nobackup
set langmenu=zh_CN.UTF-8
set filetype=python
au BufNewFile,BufRead *.py,*.pyw setf python
